variable "vpc-link-sg-name" {}
variable "vpc-name" {}
variable "ssm-ec2-sg-name" {}
variable "alb-sg-name" {}
variable "redis-ec2-sg-name" {}
variable "eks-cluster-sg-name" {}
variable "eks-node-sg-name" {}
variable "postgre-db-sg-name" {}
variable "document-db-sg-name" {}
